version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@3.1.5
  aws-s3: circleci/aws-s3@3.0.0

executors:
  test-executor:
    docker:
      - image: circleci/node:14.18.0-browsers
    working_directory: /tmp/cvLiveS3

commands:
  checkout-cache-install:
    description: "create the folder dist"
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - run: yarn build

  sync-to-s3:
    description: "Sync the dist folder to S3 bucket"
    steps:
      - aws-s3/sync:
          arguments: |
            --cache-control "max-age=86400"
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-region: $AWS_REGION
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          from: /tmp/cvLiveS3/dist
          to: 's3://cv.jonaskabalo.com'
          overwrite: true
      - aws-s3/copy:
          arguments: '--dryrun'
          from: /tmp/cvLiveS3/dist
          to: 's3://cv.jonaskabalo.com'

  invalidate-cloudfront:
    description: "Invalidate CloudFront distribution"
    steps:
      - run:
          name: Create CloudFront invalidation
          command: |
            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

jobs:
  test:
    executor: node/default
    steps:
      - checkout-cache-install

  publish:
    executor: node/default
    steps:
      - checkout-cache-install
      - sync-to-s3:
          requires:
            - checkout-cache-install
      - aws-cli/install
      - invalidate-cloudfront:
          requires:
            - aws-cli/install
          environment:
            CLOUDFRONT_DISTRIBUTION_ID: $CLOUDFRONT_DISTRIBUTION_ID

workflows:
  version: 2
  test-and-publish:
    jobs:
      - test
      - publish:
          filters:
            branches:
              only:
                - main
          requires:
            - test
